# Generated by Django 4.0.5 on 2022-07-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('person_img', models.ImageField(default='', upload_to='personImages/')),
                ('conf_score', models.FloatField()),
            ],
        ),
    ]
