# Generated by Django 4.0.5 on 2022-07-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='face_img',
            field=models.ImageField(blank=True, null=True, upload_to='personImages/'),
        ),
    ]
