# Generated by Django 4.0.5 on 2022-07-14 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_merge_20220412_2024'),
        ('imagesApp', '0002_person_face_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='camera_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cameras.camera'),
        ),
    ]
