# Generated by Django 4.0.2 on 2022-02-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinecameras',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offlinecameras',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
