# Generated by Django 4.0.2 on 2022-04-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_remove_camera_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='name',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
