# Generated by Django 4.0.2 on 2022-04-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_camera_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='location',
            field=models.CharField(default='undefined', max_length=300),
        ),
    ]
