# Generated by Django 3.0.5 on 2022-04-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_offlinecameras_sms_sent_alter_offlinecameras_time'),
        ('cameras', '0004_camera_location'),
    ]

    operations = [
    ]
